sonar.projectKey=devops-portfolio-mern
sonar.projectName=devops-portfolio-mern
sonar.sourceEncoding=UTF-8

sonar.sources=frontend/src,backend/src,backend/server.js
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,backend/uploads/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
